name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: kenranunderscore
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: no
          config_timezone: Europe/Berlin
          optimize: no
          repositories_forks: yes
          use_prebuilt_image: yes

          plugin_activity_days: 0

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 0

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

          plugin_repositories: yes
          plugin_repositories_featured: kenranunderscore/dotfiles, nixos/nixpkgs, crawl/crawl
